<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WaxyCandles.PricePollingWorker-a61256d0-ac0f-4c48-8ec3-dd1d16b2792c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WaxyCandles.Application\WaxyCandles.Application.csproj" />
    <ProjectReference Include="..\WaxyCandles.Infrastructure\WaxyCandles.Infrastructure.csproj" />
  </ItemGroup>
</Project>
