/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/alerts'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardWatchlistRouteImport } from './routes/_dashboard/watchlist'
import { Route as DashboardStocksSymbolRouteImport } from './routes/_dashboard/stocks/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWatchlistRoute = DashboardWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStocksSymbolRoute = DashboardStocksSymbolRouteImport.update({
  id: '/stocks/$symbol',
  path: '/stocks/$symbol',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof DashboardAlertsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/watchlist': typeof DashboardWatchlistRoute
  '/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof DashboardAlertsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/watchlist': typeof DashboardWatchlistRoute
  '/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/watchlist': typeof DashboardWatchlistRoute
  '/_dashboard/stocks/$symbol': typeof DashboardStocksSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/alerts' | '/dashboard' | '/watchlist' | '/stocks/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/login' | '/alerts' | '/dashboard' | '/watchlist' | '/stocks/$symbol'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/alerts'
    | '/_dashboard/dashboard'
    | '/_dashboard/watchlist'
    | '/_dashboard/stocks/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/watchlist': {
      id: '/_dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof DashboardWatchlistRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/stocks/$symbol': {
      id: '/_dashboard/stocks/$symbol'
      path: '/stocks/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof DashboardStocksSymbolRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardWatchlistRoute: typeof DashboardWatchlistRoute
  DashboardStocksSymbolRoute: typeof DashboardStocksSymbolRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardWatchlistRoute: DashboardWatchlistRoute,
  DashboardStocksSymbolRoute: DashboardStocksSymbolRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
